---
- name: start a Metabase container
  docker_container:
    image: metabase/metabase
    state: started
    hostname: "{{ ansible_hostname }}-metabase"
    ports:
      - "{{ metabase_port }}:3000"
    name: "{{ metabase_container_name }}"
    restart_policy: always
    env:
      MB_DB_TYPE: "{{ metabase_db_type }}"
      MB_DB_DBNAME: "{{ metabase_db_name }}"
      MB_DB_PORT: "{{ metabase_db_port }}"
      MB_DB_USER: "{{ metabase_db_user }}"
      MB_DB_PASS: "{{ metabase_db_password }}"
      MB_DB_HOST: "{{ metabase_db_host }}"
